diff_drive_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: wheel_left_joint
    right_wheel: wheel_right_joint
    wheel_separation: 0.32
    wheel_radius: 0.051
    linear/x/max_velocity: 0.5
    angular/z/max_velocity: 1.0