<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" >

<xacro:property name="base_length" value="0.6" />
<xacro:property name="base_width" value="0.4" />
<xacro:property name="base_hight" value="0.2" />
<xacro:property name="wheel_r" value="0.1" />
<xacro:property name="wheel_length" value="0.05" />


<inertial>
  <mass value="1.0"/>
  <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
</inertial>


    <link name="base_footprint">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_hight}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_hight/2.0}" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_hight}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_hight/2.0}" rpy="0.0 0.0 0.0"/>
        </collision>

        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_hight}" xyz="0.0 0.0 ${base_hight/2.0}" rpy="0.0 0.0 0.0"/>
    </link>

    <link name="lidar_link">
        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
             <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
        </collision>
    </link>

    <link name="left_wheel_link">
     <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_length}"/>
        </geometry>
        <material name="grey"/>
     </visual> 
     <collision>
         <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_length}"/>
        </geometry>
     </collision>   
     <xacro:cylinder_inertia m="1.0" r="${2*wheel_r}" h="${2*wheel_length}" xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0" />
    </link>

    <link name="right_wheel_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_length}"/>
        </geometry>
        <material name="grey"/>
    </visual>    
   <collision>
        <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_length}"/>
        </geometry>
   </collision>
    <xacro:cylinder_inertia m="1.0" r="${2*wheel_r}" h="${2*wheel_length}" xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0" />
    </link>

<link name="caster_link">
    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <sphere radius="${wheel_r / 2.0}"/>
        </geometry>
        <material name="grey"/>
    </visual>
    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <sphere radius="${wheel_r / 2.0}"/>
        </geometry> 
    </collision>
    <xacro:sphere_inertia m="0.5" r="${2*wheel_r / 2.0}" xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
</link>

<link name="camera_link">
  <visual>
   <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <geometry>
      <box size="0.025 0.025 0.025"/>
    </geometry>
    <material name="grey"/>
  </visual>
</link>

<joint name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 ${wheel_r}" rpy="0.0 0.0 0.0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
   
</joint>

    <joint name="base_lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.0 0.0 0.225" rpy="0.0 0.0 0.0"/>        
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length)/2.0} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 1 0.0"/>
    </joint>

     <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length)/2.0} 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 1 0.0"/>
    </joint>

    <joint name="caster_joint" type="fixed">
        <origin xyz="${base_length/3.0} 0.0 ${-(wheel_r / 2.0)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="caster_link"/>
    </joint>

    <joint name="camera_joint" type="fixed">
  <parent link="base_link"/>
  <child link="camera_link"/>
  <origin xyz="0.32 0 0.1" rpy="0 0 0"/>
</joint>

<gazebo reference="camera_link">
  <sensor type="camera" name="camera_sensor">
    <pose>0 0 0 0 0 0</pose>
    <camera>
      <horizontal_fov>1.57</horizontal_fov>
      <image>
        <width>640</width>
        <height>480</height>
        <format>R8G8B8</format>
      </image>
      <clip>
        <near>0.1</near>
        <far>100</far>
      </clip>
    </camera>
    <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
     <cameraName>camera_sensor</cameraName>
  <ros>
    <namespace>/my_robot</namespace>
    <argument>camera</argument>
  </ros>
</plugin>
  </sensor>
</gazebo>

<gazebo reference="lidar_link">
  <sensor type="ray" name="lidar_sensor">
    <pose>0 0 0 0 0 0</pose>
    <ray>
      <scan>
        <horizontal>
          <samples>360</samples>
          <resolution>1</resolution>
          <min_angle>-1.57</min_angle>
          <max_angle>1.57</max_angle>
        </horizontal>
      </scan>
      <range>
        <min>0.1</min>
        <max>10.0</max>
        <resolution>0.01</resolution>
      </range>
    </ray>
    <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so"/>
  </sensor>
</gazebo>

</robot>